const supportedLanguages = [
  ["zh", "Chinese"], ["en", "English"], ["yue", "Cantonese"], ["ar", "Arabic"],
  ["de", "German"], ["fr", "French"], ["es", "Spanish"], ["pt", "Portuguese"],
  ["id", "Indonesian"], ["it", "Italian"], ["ko", "Korean"], ["ru", "Russian"],
  ["th", "Thai"], ["vi", "Vietnamese"], ["ja", "Japanese"], ["tr", "Turkish"],
  ["hi", "Hindi"], ["ms", "Malay"], ["nl", "Dutch"], ["sv", "Swedish"],
  ["da", "Danish"], ["fi", "Finnish"], ["pl", "Polish"], ["cs", "Czech"],
  ["fil", "Filipino"], ["fa", "Persian"], ["el", "Greek"], ["ro", "Romanian"],
  ["hu", "Hungarian"], ["mk", "Macedonian"]
];

const english = {
  seoTitle: "CoveType — Private AI Voice Typing for Mac", seoDescription: "Free, open-source AI voice typing for Mac. Local Qwen speech-to-text, private AI polishing, 30 languages, and Apple on-device translation.",
  navFeatures: "Features", navWhy: "Why CoveType", navPrivacy: "Privacy", navLanguages: "Languages", navOpenSource: "Open source", navInstall: "Install", languageSelector: "Website language", downloadShort: "Download",
  eyebrow: "PRIVATE · LOCAL · AI", heroTitle: "Private AI voice typing for Mac. Your voice stays local.", heroText: "Hold a shortcut to speak and release it to type in any app. CoveType runs Qwen speech-to-text and AI polishing locally, detects 30 languages, and supports Apple on-device translation.", downloadMac: "Download for macOS", readPrivacy: "Read the privacy details", appleSilicon: "Apple silicon (M1+)", noAccount: "No account", freeOpenSource: "Free & open source", listening: "Listening", releaseToType: "Release to transcribe and type", processedLocally: "Processed locally",
  featuresEyebrow: "WHAT IT DOES", featuresTitle: "Voice input without the cloud detour.",
  features: [
    ["Local transcription", "Qwen3-ASR 0.6B 8-bit runs on Apple silicon and automatically detects 30 languages."],
    ["Local AI polishing", "Qwen3.5 0.8B 4-bit can improve punctuation, sentence breaks, and spoken phrasing without a cloud writing API."],
    ["Instant translation", "Speak one language and output another through Apple Translation and downloaded on-device language packs."],
    ["Custom hold-to-talk", "Record a key or key combination and set the hold duration so normal shortcuts do not trigger recording."],
    ["Works across apps", "Release the shortcut and CoveType inserts the result at the cursor in your current application."],
    ["Made for the menu bar", "A small breathing lamp shows idle, listening, processing, and completion states. CoveType can start at login."]
  ],
  painEyebrow: "BUILT AROUND REAL PROBLEMS", painTitle: "AI dictation without the usual privacy and workflow trade-offs.", painIntro: "Cloud voice typing can expose sensitive speech, add network delay, produce messy text, and interrupt everyday shortcuts. CoveType is designed around those pain points.",
  painPoints: [
    ["Worried about voice privacy?", "Speech recognition and AI cleanup run on your Mac instead of sending daily dictation to a cloud transcription service."],
    ["Waiting on cloud results?", "Local models remove the round trip to a remote ASR or writing API and continue working without an internet connection."],
    ["Raw transcripts need cleanup?", "An optional local Qwen model improves punctuation, sentence breaks, and spoken phrasing before text reaches your app."],
    ["Shortcuts trigger by accident?", "Record your preferred key or key combination and set a hold delay so shortcuts such as Control-C keep behaving normally."]
  ],
  comparisonTitle: "CoveType compared with typical cloud AI voice typing", comparisonCapability: "Capability", comparisonCloud: "Typical cloud dictation",
  comparisons: [["Speech-to-text", "Runs locally on your Mac", "Audio is uploaded for processing"], ["AI text polishing", "Local Qwen model", "Often handled by a cloud LLM"], ["Translation", "Apple on-device framework", "Often a remote translation API"], ["Account", "Not required", "Commonly required"], ["Source code", "Open source under GPLv3", "Usually proprietary"]],
  privacyEyebrow: "PRIVACY & SECURITY", privacyTitle: "A local processing path you can understand.", privacyIntro: "Daily transcription and AI polishing do not call cloud ASR or cloud writing APIs. Recording starts only after your configured shortcut is intentionally held.",
  privacy: [
    ["Audio stays local", "Temporary recordings are processed on the Mac and cleaned up after the workflow finishes."],
    ["Models stay local", "Qwen3-ASR and Qwen3.5 are stored in CoveType’s local application data."],
    ["No account or sync", "CoveType does not need a login and does not synchronize your transcript history."],
    ["Permissions are limited", "Microphone captures speech; Accessibility listens for the global shortcut and inserts text into the active app."]
  ],
  networkTitle: "When is a network connection used?", networkText: "The first installation downloads the pinned runtime and models. macOS downloads Apple Translation language packs when needed. A configured update check may contact the release endpoint. Normal transcription and polishing remain local.", telemetryTitle: "Anonymous daily usage statistics", telemetryText: "Enabled by default and switchable in the Send Feedback window. At most once every 24 hours, CoveType sends a random installation ID, app version, macOS version, and processor architecture over HTTPS. Cloudflare derives the country; CoveType does not store the raw IP. Audio, transcripts, and typed text are never included.",
  flowTitle: "Your local voice-to-text path", localFlow: [["Speak", "Recording starts only while your chosen shortcut is held."], ["Transcribe locally", "Qwen3-ASR converts speech to text on the Mac."], ["Polish locally", "Optional Qwen3.5 cleanup improves readability on device."], ["Translate or type", "Use Apple on-device translation or insert the result into the active app."]],
  openEyebrow: "OPEN SOURCE BY DESIGN", openTitle: "Privacy claims you can inspect—not just trust.", openIntro: "CoveType’s macOS application code is public under GPLv3. Review how recording starts, where models run, when networking is used, and how text is inserted into other apps.", viewSource: "View source code on GitHub",
  proofs: [["Auditable", "Inspect the Swift client, local AI worker, installer, update channel, and permission handling."], ["No account", "No sign-up, subscription identity, or transcript sync is required for everyday voice typing."], ["Clear network boundary", "The first install, translation language packs, updates, GitHub feedback, and source links can use the network. Daily transcription and polishing stay local."]],
  languagesEyebrow: "LANGUAGE SUPPORT", languagesTitle: "30 languages, detected automatically.", languagesIntro: "This is the exact recognition list reported by the installed Qwen3-ASR model. Cantonese is listed separately from Chinese. You do not need to select the spoken language before recording.", translationTitle: "Translation output is a separate capability.", translationText: "The recognition list above does not guarantee the same 30 translation targets. Available Apple on-device translation pairs depend on the macOS version, region, and language packs installed by the user.",
  installEyebrow: "DOWNLOAD & INSTALL", installTitle: "One guided installer for Apple silicon Macs.", requirementsTitle: "Requirements", computer: "Computer", computerValue: "Mac with M1 or newer Apple silicon", system: "System", memory: "Memory", memoryValue: "8 GB workable; 16 GB recommended", storage: "Storage", storageValue: "At least 5 GB free", firstInstall: "First install", firstInstallValue: "Internet connection; no administrator password required",
  installSteps: [["Download and unzip", "Open the CoveType installer ZIP and extract it."], ["Run the installer", "Open “Install CoveType.command”. It installs the app, isolated runtime, models, and login item."], ["Approve two permissions", "Follow the system-language guide to enable Microphone and Accessibility. The installer checks both."]],
  downloadBuild: "macOS 15+ · Apple silicon · Apple-notarized installer ZIP", downloadNow: "Download now",
  windowsEyebrow: "WINDOWS STATUS", windowsTitle: "The current app does not support Windows.", windowsIntro: "The downloadable client depends on macOS-only AppKit/SwiftUI, AVFoundation, Accessibility APIs, Apple Translation, and MLX. It cannot be copied or repackaged for Windows.", windowsAvailableTitle: "What works on Windows today?", windowsAvailableText: "The source repository includes a Windows 10/11 x64 bootstrap for the official Qwen3-ASR PyTorch backend and a browser microphone demo. It is a local recognition test, not yet a system-wide tray input app.", windowsNeedsTitle: "What is required for a complete Windows release?", windowsNeedsText: "A separate .NET 8 desktop client, WASAPI recording, Windows global hotkeys and SendInput, a PyTorch/ONNX model runtime, a local translation replacement, a signed installer, and testing on real Windows 10/11 systems. Practical target: x64, 8 GB RAM minimum, 16 GB recommended, 8–10 GB free disk; an NVIDIA GPU is optional but strongly improves latency.",
  faqEyebrow: "DETAILS", faqTitle: "Before you install", faqs: [["Does CoveType send my voice or transcript to the cloud?", "Normal speech recognition and optional AI polishing run locally on your Mac. The first installation downloads models, Apple may download translation language packs, and update checks contact the CoveType release endpoint."], ["Can CoveType voice typing work offline?", "Yes. After the runtime, Qwen models, and any required Apple translation packs have been downloaded, normal transcription and local AI polishing work without an internet connection."], ["Is CoveType free and open source?", "Yes. The CoveType application source is available under GPLv3. Qwen models, Python packages, and Apple frameworks keep their own licenses and terms."], ["Does it type into any Mac app?", "CoveType inserts the result at the current cursor using macOS Accessibility APIs, so it works across editors, browsers, email, chat, documents, and many developer tools."], ["Is CoveType a full macOS input method?", "No. It is a menu-bar voice input utility with a system-wide hold-to-talk shortcut, so you do not need to switch keyboard input sources."], ["Why does it need Accessibility permission?", "macOS requires this permission for global shortcut handling and for inserting text into another active application. You can revoke it at any time in System Settings."], ["Does local AI polishing support all 30 recognition languages equally?", "No. Qwen3.5 is multilingual, but polishing quality is not identical across all languages. Recognition support and rewriting quality are separate; test important language workflows first."]],
  footerTagline: "Private voice typing, built for your Mac.", windowsStatusLink: "Windows status"
};

const locales = {
  en: english,
  "zh-Hans": {
    ...english,
    seoTitle:"CoveType — Mac 本地 AI 语音输入与语音转文字",seoDescription:"免费开源的 Mac AI 语音输入工具。本地 Qwen 语音转文字与 AI 润色，自动识别 30 种语言，支持 Apple 设备端翻译。",navFeatures:"功能",navWhy:"为什么选择",navPrivacy:"隐私",navLanguages:"语言",navOpenSource:"开源",navInstall:"安装",languageSelector:"网站语言",downloadShort:"下载",eyebrow:"隐私 · 本地 · AI",heroTitle:"Mac 本地 AI 语音输入。你的声音只留在本机。",heroText:"按住快捷键说话，松开即可在任意应用输入。CoveType 在本地运行 Qwen 语音转文字与 AI 润色，自动识别 30 种语言，并支持 Apple 设备端翻译。",downloadMac:"下载 macOS 版",readPrivacy:"查看隐私说明",appleSilicon:"Apple 芯片（M1+）",noAccount:"无需账号",freeOpenSource:"免费开源",listening:"正在聆听",releaseToType:"松开后识别并输入",processedLocally:"本地处理",
    featuresEyebrow:"核心功能",featuresTitle:"不绕云端的语音输入。",features:[["本地语音识别","Qwen3-ASR 0.6B 8-bit 在 Apple 芯片上运行，并自动检测 30 种语言。"],["本地 AI 润色","Qwen3.5 0.8B 4-bit 可整理标点、断句和口语表达，不调用云端写作 API。"],["即时翻译","说一种语言，通过 Apple Translation 与已下载的设备端语言包输出另一种语言。"],["自定义按住说话","录制单键或组合键并设置按住时长，避免常用快捷键误触录音。"],["跨应用输入","松开快捷键后，CoveType 将结果插入当前应用的光标位置。"],["菜单栏常驻","小型呼吸灯显示空闲、聆听、处理和完成状态，并可登录后自动启动。"]],
    painEyebrow:"解决真实问题",painTitle:"摆脱云端 AI 语音输入的隐私与工作流负担。",painIntro:"云端语音输入可能暴露敏感内容、增加网络延迟、输出凌乱文字，并与常用快捷键冲突。CoveType 针对这些痛点设计。",painPoints:[["担心语音隐私？","语音识别和 AI 润色都在 Mac 本地运行，日常口述不会发送到云端转录服务。"],["不想等待云端返回？","本地模型省去远程 ASR 和写作 API 往返，离线时仍可使用。"],["原始转录太凌乱？","可选本地 Qwen 模型会在输入前改善标点、断句和口语表达。"],["快捷键经常误触？","可录制单键或组合键并设置按住延迟，确保 Control-C 等常用快捷键正常工作。"]],comparisonTitle:"CoveType 与常见云端 AI 语音输入对比",comparisonCapability:"能力",comparisonCloud:"常见云端语音输入",comparisons:[["语音转文字","在 Mac 本地运行","上传音频后处理"],["AI 文字润色","本地 Qwen 模型","通常由云端大模型处理"],["翻译","Apple 设备端框架","通常调用远程翻译 API"],["账号","不需要","通常需要"],["源代码","GPLv3 开源","通常闭源"]],
    privacyEyebrow:"隐私与安全",privacyTitle:"看得懂的本地处理路径。",privacyIntro:"日常转录与 AI 润色不调用云端语音识别或云端写作 API。只有主动按住已配置快捷键后才开始录音。",privacy:[["音频留在本地","临时录音在 Mac 上处理，流程结束后清理。"],["模型留在本地","Qwen3-ASR 与 Qwen3.5 保存在 CoveType 的本地应用数据中。"],["无需账号与同步","CoveType 不要求登录，也不会同步转录历史。"],["权限用途有限","麦克风用于采集语音；辅助功能用于全局快捷键和向当前应用输入文字。"]],networkTitle:"什么时候会联网？",networkText:"首次安装会下载固定版本的运行环境和模型；macOS 会按需下载 Apple Translation 语言包；配置更新通道后，更新检查可能访问发布地址。日常识别与润色仍在本地完成。",telemetryTitle:"匿名每日使用统计",telemetryText:"默认开启，可在客户端“使用反馈”窗口中关闭。CoveType 每 24 小时最多通过 HTTPS 发送一次随机安装编号、应用版本、macOS 版本和处理器架构；Cloudflare 仅判断国家，CoveType 不保存原始 IP。绝不包含录音、转录结果或输入文字。",
    flowTitle:"你的本地语音转文字路径",localFlow:[["说话","只有按住所选快捷键时才开始录音。"],["本地转录","Qwen3-ASR 在 Mac 上把语音转换为文字。"],["本地润色","可选 Qwen3.5 在设备端改善可读性。"],["翻译或输入","通过 Apple 设备端翻译，或把结果插入当前应用。"]],openEyebrow:"为开源而设计",openTitle:"隐私承诺可以检查，不必盲目信任。",openIntro:"CoveType 的 macOS 应用代码按 GPLv3 公开。你可以检查录音何时开始、模型在哪里运行、什么时候联网，以及文字如何插入其他应用。",viewSource:"在 GitHub 查看源代码",proofs:[["可审计","检查 Swift 客户端、本地 AI 工作进程、安装器、更新通道和权限处理。"],["无需账号","日常语音输入不要求注册、订阅身份或同步转录记录。"],["清晰的网络边界","首次安装、翻译语言包、更新、GitHub 反馈和源码链接可能联网；日常识别与润色始终在本地。"]],
    languagesEyebrow:"语言支持",languagesTitle:"自动检测 30 种语言。",languagesIntro:"以下是本机已安装 Qwen3-ASR 模型报告的准确识别清单，粤语与中文分开列出。录音前无需手动选择口语。",translationTitle:"翻译输出是另一项独立能力。",translationText:"识别支持 30 种语言，不等于 Apple 翻译也支持完全相同的 30 个目标语种。实际翻译语言组合取决于 macOS 版本、地区和用户已安装的语言包。",
    installEyebrow:"下载与安装",installTitle:"面向 Apple 芯片 Mac 的引导式安装器。",requirementsTitle:"系统要求",computer:"电脑",computerValue:"M1 或更新 Apple 芯片 Mac",system:"系统",memory:"内存",memoryValue:"8 GB 可运行；建议 16 GB",storage:"空间",storageValue:"至少 5 GB 可用空间",firstInstall:"首次安装",firstInstallValue:"需要网络连接；无需管理员密码",installSteps:[["下载并解压","下载 CoveType 安装器 ZIP 后解压。"],["运行安装器","打开“Install CoveType.command”，它会安装应用、独立运行环境、模型和开机启动项。"],["开启两个权限","按系统语言提示开启麦克风和辅助功能；安装器会检测结果。"]],downloadBuild:"macOS 15+ · Apple 芯片 · Apple 公证 ZIP 安装器",downloadNow:"立即下载",
    windowsEyebrow:"WINDOWS 状态",windowsTitle:"当前应用不支持 Windows。",windowsIntro:"当前可下载客户端依赖 macOS 专属的 AppKit/SwiftUI、AVFoundation、辅助功能 API、Apple Translation 与 MLX，不能直接复制或重新打包到 Windows。",windowsAvailableTitle:"现在 Windows 上能用什么？",windowsAvailableText:"源码仓库已包含适用于 Windows 10/11 x64 的官方 Qwen3-ASR PyTorch 后端安装脚本和浏览器麦克风测试页。它能进行本地识别测试，但还不是能在任意软件输入的系统托盘客户端。",windowsNeedsTitle:"完整 Windows 版需要什么？",windowsNeedsText:"需要另做 .NET 8 桌面客户端、WASAPI 录音、Windows 全局快捷键与 SendInput、PyTorch/ONNX 模型运行环境、本地翻译替代方案、签名安装器，并在真实 Windows 10/11 机器测试。建议目标配置：x64，最低 8 GB 内存、推荐 16 GB，8–10 GB 可用空间；NVIDIA 显卡不是必需，但能明显降低延迟。",
    faqEyebrow:"详细说明",faqTitle:"安装前须知",faqs:[["CoveType 会把语音或转录文字发送到云端吗？","日常语音识别和可选 AI 润色都在 Mac 本地运行。首次安装需要下载模型，Apple 可能下载翻译语言包，更新检查会访问 CoveType 发布地址。"],["CoveType 可以离线语音输入吗？","可以。运行环境、Qwen 模型和所需 Apple 翻译语言包下载完成后，日常转录与本地 AI 润色无需联网。"],["CoveType 免费并且开源吗？","是。CoveType 应用源码按 GPLv3 开放；Qwen 模型、Python 软件包和 Apple 框架各自保留原许可。"],["可以在任意 Mac 应用输入吗？","CoveType 通过 macOS 辅助功能 API 在当前光标处输入，可用于编辑器、浏览器、邮件、聊天、文档和许多开发工具。"],["CoveType 是完整的 macOS 输入法吗？","不是。它是带全局按住说话快捷键的菜单栏语音输入工具，无需切换系统输入源。"],["为什么需要辅助功能权限？","macOS 要求获得此权限才能处理全局快捷键并向另一个前台应用输入文字，可随时在系统设置中撤销。"],["本地 AI 润色对 30 种识别语言效果都一样吗？","不一样。Qwen3.5 支持多语言，但不同语言的润色质量存在差异。识别支持和改写质量是两回事，重要流程请先测试。"]],footerTagline:"为 Mac 打造的隐私语音输入。",windowsStatusLink:"Windows 状态"
  },
  "zh-Hant": {
    ...english,
    seoTitle:"CoveType — Mac 本機 AI 語音輸入與語音轉文字",seoDescription:"免費開源的 Mac AI 語音輸入工具。本機 Qwen 語音轉文字與 AI 潤飾，自動辨識 30 種語言，支援 Apple 裝置端翻譯。",navFeatures:"功能",navWhy:"為何選擇",navPrivacy:"私隱",navLanguages:"語言",navOpenSource:"開源",navInstall:"安裝",languageSelector:"網站語言",downloadShort:"下載",eyebrow:"私隱 · 本機 · AI",heroTitle:"Mac 本機 AI 語音輸入。你的聲音只留在本機。",heroText:"按住快捷鍵說話，放開即可在任何應用程式輸入。CoveType 在本機執行 Qwen 語音轉文字與 AI 潤飾，自動辨識 30 種語言，並支援 Apple 裝置端翻譯。",downloadMac:"下載 macOS 版",readPrivacy:"查看私隱說明",appleSilicon:"Apple 晶片（M1+）",noAccount:"無需帳號",freeOpenSource:"免費開源",listening:"正在聆聽",releaseToType:"放開後辨識並輸入",processedLocally:"本機處理",
    featuresEyebrow:"核心功能",featuresTitle:"不繞雲端的語音輸入。",features:[["本機語音辨識","Qwen3-ASR 0.6B 8-bit 在 Apple 晶片上執行，並自動偵測 30 種語言。"],["本機 AI 潤飾","Qwen3.5 0.8B 4-bit 可整理標點、斷句與口語表達，不呼叫雲端寫作 API。"],["即時翻譯","說一種語言，透過 Apple Translation 與已下載的裝置端語言套件輸出另一種語言。"],["自訂按住說話","錄製單鍵或組合鍵並設定按住時間，避免常用快捷鍵誤觸錄音。"],["跨應用程式輸入","放開快捷鍵後，CoveType 將結果插入目前應用程式的游標位置。"],["選單列常駐","小型呼吸燈顯示閒置、聆聽、處理與完成狀態，並可登入後自動啟動。"]],
    painEyebrow:"解決真實問題",painTitle:"擺脫雲端 AI 語音輸入的私隱與工作流程負擔。",painIntro:"雲端語音輸入可能暴露敏感內容、增加網絡延遲、輸出凌亂文字，並與常用快捷鍵衝突。CoveType 針對這些問題設計。",painPoints:[["擔心語音私隱？","語音辨識與 AI 潤飾均在 Mac 本機執行，日常口述不會傳送至雲端轉錄服務。"],["不想等待雲端結果？","本機模型省去遠端 ASR 與寫作 API 往返，離線時仍可使用。"],["原始轉錄太凌亂？","可選本機 Qwen 模型在輸入前改善標點、斷句與口語表達。"],["快捷鍵經常誤觸？","可記錄單鍵或組合鍵並設定按住延遲，讓 Control-C 等常用快捷鍵正常運作。"]],comparisonTitle:"CoveType 與常見雲端 AI 語音輸入比較",comparisonCapability:"能力",comparisonCloud:"常見雲端語音輸入",comparisons:[["語音轉文字","在 Mac 本機執行","上傳音訊後處理"],["AI 文字潤飾","本機 Qwen 模型","通常由雲端大型語言模型處理"],["翻譯","Apple 裝置端框架","通常呼叫遠端翻譯 API"],["帳號","不需要","通常需要"],["源碼","GPLv3 開源","通常閉源"]],
    privacyEyebrow:"私隱與安全",privacyTitle:"清楚易懂的本機處理路徑。",privacyIntro:"日常轉錄與 AI 潤飾不呼叫雲端語音辨識或寫作 API。只有主動按住已設定快捷鍵後才會開始錄音。",privacy:[["音訊留在本機","暫存錄音在 Mac 上處理，流程完成後清除。"],["模型留在本機","Qwen3-ASR 與 Qwen3.5 儲存在 CoveType 的本機應用程式資料。"],["無需帳號與同步","CoveType 不要求登入，也不會同步轉錄歷史。"],["權限用途有限","咪高峰用於擷取語音；輔助使用權限用於全域快捷鍵及向目前應用程式輸入文字。"]],networkTitle:"何時會使用網路？",networkText:"首次安裝會下載固定版本的執行環境與模型；macOS 會按需要下載 Apple Translation 語言套件；設定更新通道後，更新檢查可能連線到發佈位址。日常辨識與潤飾仍在本機完成。",telemetryTitle:"匿名每日使用統計",telemetryText:"預設開啟，可在用戶端「使用回饋」視窗中關閉。CoveType 每 24 小時最多透過 HTTPS 傳送一次隨機安裝編號、應用程式版本、macOS 版本和處理器架構；Cloudflare 只判斷國家，CoveType 不儲存原始 IP。絕不包含錄音、轉錄結果或輸入文字。",
    flowTitle:"你的本機語音轉文字路徑",localFlow:[["說話","只有按住所選快捷鍵時才開始錄音。"],["本機轉錄","Qwen3-ASR 在 Mac 上把語音轉換為文字。"],["本機潤飾","可選 Qwen3.5 在裝置端改善可讀性。"],["翻譯或輸入","透過 Apple 裝置端翻譯，或將結果插入目前應用程式。"]],openEyebrow:"為開源而設計",openTitle:"私隱承諾可以檢查，不必盲目信任。",openIntro:"CoveType 的 macOS 應用程式碼按 GPLv3 公開。你可檢查錄音何時開始、模型在哪裡執行、何時連網，以及文字如何插入其他應用程式。",viewSource:"在 GitHub 查看源碼",proofs:[["可審核","檢查 Swift 客戶端、本機 AI 工作程序、安裝程式、更新通道與權限處理。"],["無需帳號","日常語音輸入不要求註冊、訂閱身分或同步轉錄記錄。"],["清晰網絡邊界","首次安裝、翻譯語言包、更新、GitHub 意見和源碼連結可能連網；日常辨識與潤飾留在本機。"]],
    languagesEyebrow:"語言支援",languagesTitle:"自動偵測 30 種語言。",languagesIntro:"以下是本機已安裝 Qwen3-ASR 模型回報的準確辨識清單，粵語與中文分開列出。錄音前無需手動選擇口語。",translationTitle:"翻譯輸出是另一項獨立功能。",translationText:"辨識支援 30 種語言，不代表 Apple 翻譯亦支援完全相同的 30 個目標語言。實際翻譯組合取決於 macOS 版本、地區及已安裝的語言套件。",
    installEyebrow:"下載與安裝",installTitle:"適用於 Apple 晶片 Mac 的引導式安裝程式。",requirementsTitle:"系統要求",computer:"電腦",computerValue:"M1 或更新 Apple 晶片 Mac",system:"系統",memory:"記憶體",memoryValue:"8 GB 可執行；建議 16 GB",storage:"空間",storageValue:"至少 5 GB 可用空間",firstInstall:"首次安裝",firstInstallValue:"需要網路連線；無需管理員密碼",installSteps:[["下載並解壓縮","下載 CoveType 安裝程式 ZIP 後解壓縮。"],["執行安裝程式","開啟「Install CoveType.command」，它會安裝應用程式、獨立執行環境、模型與登入啟動項目。"],["開啟兩項權限","依系統語言提示開啟咪高峰與輔助使用權限；安裝程式會檢查結果。"]],downloadBuild:"macOS 15+ · Apple 晶片 · Apple 公證 ZIP 安裝程式",downloadNow:"立即下載",
    windowsEyebrow:"WINDOWS 狀態",windowsTitle:"目前應用程式不支援 Windows。",windowsIntro:"目前下載版依賴 macOS 專用 AppKit/SwiftUI、AVFoundation、輔助使用 API、Apple Translation 與 MLX，無法直接複製或重新封裝到 Windows。",windowsAvailableTitle:"目前 Windows 上可使用甚麼？",windowsAvailableText:"源碼庫已包含適用於 Windows 10/11 x64 的官方 Qwen3-ASR PyTorch 後端安裝腳本與瀏覽器咪高峰測試頁。它能進行本機辨識測試，但尚不是全系統托盤輸入工具。",windowsNeedsTitle:"完整 Windows 版需要甚麼？",windowsNeedsText:"需要獨立開發 .NET 8 桌面客戶端、WASAPI 錄音、Windows 全域快捷鍵與 SendInput、PyTorch/ONNX 模型執行環境、本機翻譯方案、簽署安裝程式，並在真實 Windows 10/11 裝置測試。建議目標：x64、最低 8 GB 記憶體、建議 16 GB、8–10 GB 可用空間；NVIDIA 顯示卡非必要但可明顯降低延遲。",
    faqEyebrow:"詳細說明",faqTitle:"安裝前須知",faqs:[["CoveType 是完整的 macOS 輸入法嗎？","不是。目前版本是選單列語音輸入工具，透過全域按住說話快捷鍵向目前應用程式插入文字，無需切換系統輸入來源。"],["為何需要輔助使用權限？","macOS 要求此權限才能處理全域快捷鍵並向另一個前景應用程式輸入文字。你可隨時在系統設定撤銷。"],["本機潤飾支援所有辨識語言嗎？","Qwen3.5 小模型具多語言能力，但 30 種辨識語言的潤飾品質並不完全相同。辨識支援與潤飾品質是兩回事。"],["所有內容都是開源嗎？","CoveType 應用程式程式碼按 GPLv3 發佈；Qwen 模型、Python 套件與 Apple 框架各自遵循其授權與條款。"]],footerTagline:"為 Mac 打造的私隱語音輸入。",windowsStatusLink:"Windows 狀態"
  }
};

const additionalLocales = {
  ja: {
    navFeatures:"機能",navPrivacy:"プライバシー",navLanguages:"言語",navInstall:"インストール",languageSelector:"サイトの言語",downloadShort:"ダウンロード",eyebrow:"プライベート · ローカル · AI",heroTitle:"あなたの声は、Mac の中だけに。",heroText:"ショートカットを押して話し、離すと入力。Qwen3-ASR のローカル文字起こし、ローカル AI 整文、Apple のオンデバイス翻訳に対応します。",downloadMac:"macOS 版をダウンロード",readPrivacy:"プライバシーの詳細",appleSilicon:"Apple シリコン（M1 以降）",noAccount:"アカウント不要",listening:"聴き取り中",releaseToType:"離すと文字起こしして入力",processedLocally:"ローカル処理",
    seoTitle:"CoveType — Mac 用プライベート AI 音声入力",seoDescription:"無料・オープンソースの Mac 用 AI 音声入力。ローカル Qwen 文字起こし、ローカル AI 整文、30言語自動検出、オンデバイス翻訳。",navWhy:"選ばれる理由",navOpenSource:"オープンソース",heroTitle:"Mac 用プライベート AI 音声入力。声はローカルに。",heroText:"ショートカットを押して話し、離すとどのアプリにも入力。Qwen 文字起こしと AI 整文をローカル実行し、30言語の自動検出と Apple オンデバイス翻訳に対応します。",freeOpenSource:"無料・オープンソース",
    featuresEyebrow:"主な機能",featuresTitle:"クラウドを経由しない音声入力。",features:[["ローカル文字起こし","Qwen3-ASR 0.6B 8-bit が Apple シリコン上で動作し、30言語を自動検出します。"],["ローカル AI 整文","Qwen3.5 0.8B 4-bit が句読点、改行、話し言葉を整えます。クラウド文章 API は使いません。"],["即時翻訳","Apple Translation とダウンロード済みのオンデバイス言語パックで、話した言語とは別の言語を出力します。"],["カスタム長押し操作","単独キーまたはキーの組み合わせと長押し時間を記録し、通常のショートカットによる誤作動を防ぎます。"],["アプリをまたいで入力","ショートカットを離すと、現在のアプリのカーソル位置に結果を挿入します。"],["メニューバー常駐","小さな呼吸ランプが待機、聴取、処理、完了を表示し、ログイン時に自動起動できます。"]],
    painEyebrow:"現実の課題から設計",painTitle:"プライバシーや操作性を犠牲にしない AI 音声入力。",painIntro:"クラウド音声入力には、機密音声の送信、通信待ち、読みづらい文章、ショートカットの誤作動という課題があります。CoveType はそれらを解決するために作られました。",painPoints:[["音声のプライバシーが不安？","音声認識と AI 整文は Mac 上で実行され、日常の音声をクラウド文字起こしへ送りません。"],["クラウドの応答待ちが遅い？","ローカルモデルは遠隔 API との往復をなくし、オフラインでも動きます。"],["生の文字起こしが読みにくい？","任意のローカル Qwen モデルが句読点、文区切り、話し言葉を整えます。"],["ショートカットが誤作動する？","キーまたは組み合わせと長押し時間を設定し、Control-C などを通常どおり使えます。"]],comparisonTitle:"CoveType と一般的なクラウド AI 音声入力",comparisonCapability:"機能",comparisonCloud:"一般的なクラウド音声入力",comparisons:[["音声からテキスト","Mac 上でローカル実行","音声をアップロードして処理"],["AI 整文","ローカル Qwen モデル","クラウド LLM が多い"],["翻訳","Apple オンデバイス","遠隔 API が多い"],["アカウント","不要","必要な場合が多い"],["ソースコード","GPLv3 で公開","通常は非公開"]],
    privacyEyebrow:"プライバシーとセキュリティ",privacyTitle:"理解できるローカル処理経路。",privacyIntro:"通常の文字起こしと AI 整文は、クラウド ASR やクラウド文章 API を呼び出しません。設定したショートカットを意図的に長押しした時だけ録音します。",privacy:[["音声はローカルに保持","一時録音は Mac で処理し、処理終了後に削除します。"],["モデルもローカル","Qwen3-ASR と Qwen3.5 は CoveType のローカルアプリデータに保存されます。"],["アカウントも同期も不要","ログインは不要で、文字起こし履歴を同期しません。"],["必要な権限のみ","マイクは音声収集、アクセシビリティはグローバルショートカットと現在のアプリへの文字入力に使います。"]],networkTitle:"ネットワークを使うのはいつ？",networkText:"初回インストールで固定バージョンの実行環境とモデルをダウンロードします。必要に応じて macOS が Apple Translation の言語パックを取得し、設定済みの更新確認がリリース先へ接続する場合があります。通常の文字起こしと整文はローカルです。",telemetryTitle:"匿名の日次利用統計",telemetryText:"既定で有効で、クライアントのフィードバック画面から無効にできます。CoveType は 24 時間に最大 1 回、ランダムなインストール ID、アプリ版、macOS 版、CPU アーキテクチャを HTTPS で送信します。Cloudflare は国だけを判定し、CoveType は生の IP を保存しません。音声、文字起こし、入力テキストは一切含みません。",
    flowTitle:"ローカル音声入力の流れ",localFlow:[["話す","選んだショートカットを押している間だけ録音します。"],["ローカル文字起こし","Qwen3-ASR が Mac 上で音声を文字にします。"],["ローカル整文","任意の Qwen3.5 が端末上で読みやすくします。"],["翻訳または入力","Apple オンデバイス翻訳を使うか、アクティブなアプリへ挿入します。"]],openEyebrow:"オープンソース設計",openTitle:"信じるだけでなく、確認できるプライバシー。",openIntro:"CoveType の macOS アプリコードは GPLv3 で公開されています。録音開始、モデル実行場所、通信のタイミング、他アプリへの入力方法を確認できます。",viewSource:"GitHub でソースを見る",proofs:[["監査可能","Swift クライアント、ローカル AI、インストーラ、更新、権限処理を確認できます。"],["アカウント不要","日常の音声入力に登録、サブスクリプション ID、履歴同期は不要です。"],["明確な通信範囲","初回導入、翻訳パック、更新、GitHub は通信しますが、日常の認識と整文はローカルです。"]],
    languagesEyebrow:"対応言語",languagesTitle:"30言語を自動検出。",languagesIntro:"以下はインストール済み Qwen3-ASR モデルが報告する正確な認識言語です。広東語は中国語とは別に記載されています。録音前の手動選択は不要です。",translationTitle:"翻訳出力は別の機能です。",translationText:"30の認識言語が、そのまま30の翻訳先を意味するわけではありません。Apple のオンデバイス翻訳で使える言語ペアは macOS のバージョン、地域、インストール済み言語パックに依存します。",
    installEyebrow:"ダウンロードとインストール",installTitle:"Apple シリコン Mac 向けガイド付きインストーラ。",requirementsTitle:"動作条件",computer:"Mac",computerValue:"M1 以降の Apple シリコン Mac",system:"OS",memory:"メモリ",memoryValue:"8 GB で動作、16 GB 推奨",storage:"空き容量",storageValue:"5 GB 以上",firstInstall:"初回導入",firstInstallValue:"インターネット接続（管理者パスワード不要）",installSteps:[["ダウンロードして展開","CoveType インストーラ ZIP をダウンロードして展開します。"],["インストーラを実行","「Install CoveType.command」を開くと、アプリ、独立した実行環境、モデル、ログイン項目を導入します。"],["2つの権限を許可","システム言語の案内に従い、マイクとアクセシビリティを有効にします。インストーラが状態を確認します。"]],downloadBuild:"macOS 15+ · Apple シリコン · Apple 公証済み ZIP",downloadNow:"今すぐダウンロード",
    windowsEyebrow:"WINDOWS の状況",windowsTitle:"現在のアプリは Windows に対応していません。",windowsIntro:"配布中のクライアントは macOS 専用の AppKit/SwiftUI、AVFoundation、アクセシビリティ API、Apple Translation、MLX に依存するため、Windows へコピーや再パッケージはできません。",windowsAvailableTitle:"現在 Windows で使えるものは？",windowsAvailableText:"ソースには Windows 10/11 x64 用の公式 Qwen3-ASR PyTorch バックエンド導入スクリプトとブラウザのマイクデモがあります。ローカル認識テストであり、システム全体で使えるトレイ入力アプリではありません。",windowsNeedsTitle:"完全な Windows 版に必要なものは？",windowsNeedsText:"別個の .NET 8 クライアント、WASAPI 録音、Windows のグローバルキーと SendInput、PyTorch/ONNX 実行環境、ローカル翻訳の代替、署名付きインストーラ、実機テストが必要です。目安は x64、最低8 GB・推奨16 GB RAM、空き8〜10 GB。NVIDIA GPU は任意ですが遅延を大きく改善します。",
    faqEyebrow:"詳細",faqTitle:"インストール前に",faqs:[["CoveType は macOS の完全な入力メソッドですか？","いいえ。現在はメニューバー型の音声入力ツールです。グローバル長押しショートカットで現在のアプリへ文字を挿入するため、入力ソースの切り替えは不要です。"],["アクセシビリティ権限が必要な理由は？","macOS ではグローバルショートカットと別アプリへの文字入力にこの権限が必要です。システム設定からいつでも取り消せます。"],["ローカル整文は全認識言語に対応しますか？","Qwen3.5 小型モデルは多言語ですが、30認識言語すべてで品質が同じではありません。認識対応と整文品質は別なので、重要な用途では事前に確認してください。"],["すべてオープンソースですか？","CoveType のアプリコードは GPLv3 です。Qwen モデル、Python パッケージ、Apple フレームワークにはそれぞれのライセンスと規約が適用されます。"]],footerTagline:"Mac のためのプライベート音声入力。",windowsStatusLink:"Windows の状況"
  },
  ko: {
    navFeatures:"기능",navPrivacy:"개인정보",navLanguages:"언어",navInstall:"설치",languageSelector:"사이트 언어",downloadShort:"다운로드",eyebrow:"비공개 · 로컬 · AI",heroTitle:"당신의 음성은 Mac 안에만 머뭅니다.",heroText:"단축키를 누른 채 말하고 놓으면 입력됩니다. 로컬 Qwen3-ASR 인식, 로컬 AI 다듬기, Apple 온디바이스 번역을 지원합니다.",downloadMac:"macOS용 다운로드",readPrivacy:"개인정보 처리 보기",appleSilicon:"Apple Silicon(M1 이상)",noAccount:"계정 불필요",listening:"듣는 중",releaseToType:"놓으면 인식 후 입력",processedLocally:"로컬 처리",
    seoTitle:"CoveType — Mac용 비공개 AI 음성 입력",seoDescription:"무료 오픈 소스 Mac AI 음성 입력. 로컬 Qwen 음성 인식, 로컬 AI 다듬기, 30개 언어 자동 감지, 온디바이스 번역.",navWhy:"CoveType의 장점",navOpenSource:"오픈 소스",heroTitle:"Mac용 비공개 AI 음성 입력. 음성은 로컬에 머뭅니다.",heroText:"단축키를 누르고 말한 뒤 놓으면 모든 앱에 입력됩니다. Qwen 음성 인식과 AI 다듬기를 로컬에서 실행하고 30개 언어 자동 감지와 Apple 온디바이스 번역을 지원합니다.",freeOpenSource:"무료 오픈 소스",
    featuresEyebrow:"주요 기능",featuresTitle:"클라우드를 우회하는 음성 입력.",features:[["로컬 음성 인식","Qwen3-ASR 0.6B 8-bit가 Apple Silicon에서 실행되며 30개 언어를 자동 감지합니다."],["로컬 AI 다듬기","Qwen3.5 0.8B 4-bit가 문장부호, 문장 구분과 구어체를 정리하며 클라우드 글쓰기 API를 사용하지 않습니다."],["즉시 번역","Apple Translation과 다운로드한 온디바이스 언어 팩으로 말한 언어와 다른 언어를 출력합니다."],["사용자 지정 누르고 말하기","단일 키나 조합키와 누르는 시간을 기록해 일반 단축키가 녹음을 작동시키지 않게 합니다."],["모든 앱에서 입력","단축키를 놓으면 현재 앱의 커서 위치에 결과를 삽입합니다."],["메뉴 막대 상주","작은 숨쉬기 램프가 대기, 듣기, 처리, 완료 상태를 표시하며 로그인 시 자동 실행할 수 있습니다."]],
    painEyebrow:"실제 문제를 위한 설계",painTitle:"개인정보와 작업 흐름을 희생하지 않는 AI 받아쓰기.",painIntro:"클라우드 음성 입력은 민감한 음성 전송, 네트워크 지연, 정리되지 않은 문장, 단축키 충돌을 만들 수 있습니다. CoveType은 이런 문제를 해결합니다.",painPoints:[["음성 개인정보가 걱정되나요?","음성 인식과 AI 다듬기는 Mac에서 실행되어 일상 음성을 클라우드 서비스로 보내지 않습니다."],["클라우드 응답이 느린가요?","로컬 모델은 원격 API 왕복을 없애고 오프라인에서도 작동합니다."],["원본 받아쓰기가 지저분한가요?","선택적 로컬 Qwen 모델이 문장부호와 구어체를 정리합니다."],["단축키가 잘못 작동하나요?","키 또는 조합과 누르는 시간을 설정해 Control-C 같은 단축키를 보호합니다."]],comparisonTitle:"CoveType과 일반 클라우드 AI 음성 입력 비교",comparisonCapability:"기능",comparisonCloud:"일반 클라우드 받아쓰기",comparisons:[["음성 인식","Mac에서 로컬 실행","오디오 업로드 후 처리"],["AI 문장 다듬기","로컬 Qwen 모델","클라우드 LLM 사용"],["번역","Apple 온디바이스","원격 API 사용"],["계정","불필요","대개 필요"],["소스 코드","GPLv3 오픈 소스","대개 비공개"]],
    privacyEyebrow:"개인정보와 보안",privacyTitle:"이해하기 쉬운 로컬 처리 경로.",privacyIntro:"일상적인 음성 인식과 AI 다듬기는 클라우드 ASR 또는 글쓰기 API를 호출하지 않습니다. 설정한 단축키를 의도적으로 누를 때만 녹음이 시작됩니다.",privacy:[["오디오는 로컬에 유지","임시 녹음은 Mac에서 처리되고 작업이 끝나면 삭제됩니다."],["모델도 로컬에 유지","Qwen3-ASR과 Qwen3.5는 CoveType의 로컬 앱 데이터에 저장됩니다."],["계정과 동기화 없음","로그인이 필요 없으며 인식 기록을 동기화하지 않습니다."],["필요한 권한만 사용","마이크는 음성 수집, 손쉬운 사용은 전역 단축키와 현재 앱의 텍스트 입력에 사용됩니다."]],networkTitle:"언제 네트워크를 사용하나요?",networkText:"최초 설치 시 고정 버전 런타임과 모델을 다운로드합니다. macOS는 필요할 때 Apple Translation 언어 팩을 다운로드하며, 구성된 업데이트 확인이 배포 주소에 연결될 수 있습니다. 일반 인식과 다듬기는 로컬에서 처리됩니다.",telemetryTitle:"익명 일일 사용 통계",telemetryText:"기본으로 켜져 있으며 클라이언트의 피드백 창에서 끌 수 있습니다. CoveType는 24시간마다 최대 한 번 임의 설치 ID, 앱 버전, macOS 버전과 프로세서 아키텍처를 HTTPS로 보냅니다. Cloudflare는 국가만 판단하며 CoveType는 원본 IP를 저장하지 않습니다. 오디오, 인식 결과와 입력 텍스트는 포함하지 않습니다.",
    flowTitle:"로컬 음성 입력 경로",localFlow:[["말하기","선택한 단축키를 누르는 동안만 녹음합니다."],["로컬 인식","Qwen3-ASR이 Mac에서 음성을 텍스트로 변환합니다."],["로컬 다듬기","선택적 Qwen3.5가 기기에서 가독성을 높입니다."],["번역 또는 입력","Apple 온디바이스 번역을 쓰거나 활성 앱에 삽입합니다."]],openEyebrow:"오픈 소스로 설계",openTitle:"믿기만 하지 않고 확인할 수 있는 개인정보 보호.",openIntro:"CoveType macOS 앱 코드는 GPLv3로 공개됩니다. 녹음 시작, 모델 위치, 네트워크 사용, 다른 앱 입력 방식을 검토할 수 있습니다.",viewSource:"GitHub에서 소스 보기",proofs:[["감사 가능","Swift 클라이언트, 로컬 AI, 설치 프로그램, 업데이트와 권한 처리를 확인합니다."],["계정 없음","일상 음성 입력에 가입, 구독 ID, 기록 동기화가 필요 없습니다."],["명확한 네트워크 경계","첫 설치, 번역 팩, 업데이트와 GitHub는 네트워크를 쓸 수 있지만 인식과 다듬기는 로컬입니다."]],
    languagesEyebrow:"지원 언어",languagesTitle:"30개 언어 자동 감지.",languagesIntro:"아래는 설치된 Qwen3-ASR 모델이 보고한 정확한 인식 목록입니다. 광둥어는 중국어와 별도로 표시됩니다. 녹음 전 언어 선택이 필요하지 않습니다.",translationTitle:"번역 출력은 별도 기능입니다.",translationText:"30개 인식 언어가 같은 30개 번역 대상을 보장하지는 않습니다. Apple 온디바이스 번역의 언어 쌍은 macOS 버전, 지역, 설치된 언어 팩에 따라 달라집니다.",
    installEyebrow:"다운로드 및 설치",installTitle:"Apple Silicon Mac용 안내 설치 프로그램.",requirementsTitle:"요구 사항",computer:"컴퓨터",computerValue:"M1 이상의 Apple Silicon Mac",system:"시스템",memory:"메모리",memoryValue:"8GB 실행 가능, 16GB 권장",storage:"저장 공간",storageValue:"최소 5GB 여유",firstInstall:"최초 설치",firstInstallValue:"인터넷 연결(관리자 암호 불필요)",installSteps:[["다운로드 및 압축 해제","CoveType 설치 ZIP을 다운로드하고 압축을 풉니다."],["설치 프로그램 실행","‘Install CoveType.command’를 열면 앱, 독립 런타임, 모델, 로그인 항목을 설치합니다."],["두 권한 허용","시스템 언어 안내에 따라 마이크와 손쉬운 사용을 켭니다. 설치 프로그램이 결과를 확인합니다."]],downloadBuild:"macOS 15+ · Apple Silicon · Apple 공증 ZIP 설치 프로그램",downloadNow:"지금 다운로드",
    windowsEyebrow:"WINDOWS 상태",windowsTitle:"현재 앱은 Windows를 지원하지 않습니다.",windowsIntro:"배포 클라이언트는 macOS 전용 AppKit/SwiftUI, AVFoundation, 손쉬운 사용 API, Apple Translation, MLX에 의존하므로 Windows에 복사하거나 다시 패키징할 수 없습니다.",windowsAvailableTitle:"현재 Windows에서 가능한 것은?",windowsAvailableText:"소스 저장소에는 Windows 10/11 x64용 공식 Qwen3-ASR PyTorch 백엔드 설치 스크립트와 브라우저 마이크 데모가 있습니다. 로컬 인식 테스트일 뿐 시스템 전체 트레이 입력 앱은 아닙니다.",windowsNeedsTitle:"완전한 Windows 버전에 필요한 것은?",windowsNeedsText:"별도 .NET 8 클라이언트, WASAPI 녹음, Windows 전역 단축키와 SendInput, PyTorch/ONNX 런타임, 로컬 번역 대체 기능, 서명된 설치 프로그램과 실제 Windows 10/11 테스트가 필요합니다. 목표 사양은 x64, 최소 8GB·권장 16GB RAM, 8~10GB 여유 공간입니다. NVIDIA GPU는 선택 사항이지만 지연을 크게 줄입니다.",
    faqEyebrow:"상세 정보",faqTitle:"설치 전 확인",faqs:[["CoveType은 완전한 macOS 입력 방식인가요?","아닙니다. 현재 버전은 메뉴 막대 음성 입력 도구입니다. 전역 누르고 말하기 단축키로 현재 앱에 텍스트를 넣으므로 입력 소스를 바꿀 필요가 없습니다."],["손쉬운 사용 권한이 왜 필요한가요?","macOS에서 전역 단축키 처리와 다른 앱의 텍스트 입력에 필요합니다. 시스템 설정에서 언제든 취소할 수 있습니다."],["로컬 다듬기가 모든 인식 언어를 지원하나요?","Qwen3.5 소형 모델은 다국어이지만 30개 인식 언어에서 품질이 동일하지 않습니다. 인식 지원과 다듬기 품질은 별개이므로 중요한 용도에서는 먼저 시험하세요."],["모두 오픈 소스인가요?","CoveType 앱 코드는 GPLv3로 배포됩니다. Qwen 모델, Python 패키지, Apple 프레임워크에는 각각의 라이선스와 약관이 적용됩니다."]],footerTagline:"Mac을 위한 비공개 음성 입력.",windowsStatusLink:"Windows 상태"
  },
  fr: {
    navFeatures:"Fonctions",navPrivacy:"Confidentialité",navLanguages:"Langues",navInstall:"Installation",languageSelector:"Langue du site",downloadShort:"Télécharger",eyebrow:"PRIVÉ · LOCAL · IA",heroTitle:"Votre voix reste sur votre Mac.",heroText:"Maintenez un raccourci pour parler, puis relâchez-le pour écrire. CoveType utilise Qwen3-ASR en local, peut reformuler avec une IA locale et traduire via le framework Apple sur l’appareil.",downloadMac:"Télécharger pour macOS",readPrivacy:"Lire les détails de confidentialité",appleSilicon:"Puce Apple (M1 ou plus)",noAccount:"Aucun compte",listening:"Écoute",releaseToType:"Relâchez pour transcrire et écrire",processedLocally:"Traitement local",
    seoTitle:"CoveType — Saisie vocale IA privée pour Mac",seoDescription:"Saisie vocale IA gratuite et open source pour Mac : transcription Qwen locale, reformulation IA privée, 30 langues et traduction sur l’appareil.",navWhy:"Pourquoi CoveType",navOpenSource:"Open source",heroTitle:"Saisie vocale IA privée pour Mac. Votre voix reste locale.",heroText:"Maintenez un raccourci, parlez et relâchez pour écrire dans toute application. Qwen transcrit et reformule localement, détecte 30 langues et prend en charge la traduction Apple sur l’appareil.",freeOpenSource:"Gratuit et open source",
    featuresEyebrow:"FONCTIONS",featuresTitle:"La saisie vocale sans détour par le cloud.",features:[["Transcription locale","Qwen3-ASR 0.6B 8-bit fonctionne sur puce Apple et détecte automatiquement 30 langues."],["Reformulation IA locale","Qwen3.5 0.8B 4-bit améliore ponctuation, phrases et style oral sans API de rédaction cloud."],["Traduction instantanée","Parlez dans une langue et produisez-en une autre avec Apple Translation et les packs téléchargés sur l’appareil."],["Appuyer pour parler personnalisable","Enregistrez une touche ou combinaison et sa durée d’appui pour éviter les déclenchements accidentels."],["Fonctionne dans les applications","Relâchez le raccourci et CoveType insère le résultat à la position du curseur."],["Conçu pour la barre des menus","Une petite lampe indique veille, écoute, traitement et fin. CoveType peut démarrer à l’ouverture de session."]],
    painEyebrow:"CONÇU POUR DE VRAIS PROBLÈMES",painTitle:"La dictée IA sans compromis sur la confidentialité ni le flux de travail.",painIntro:"La saisie vocale cloud peut exposer des propos sensibles, ajouter de la latence, produire un texte brut et perturber les raccourcis. CoveType répond à ces problèmes.",painPoints:[["La confidentialité de votre voix vous préoccupe ?","La reconnaissance et la reformulation IA s’exécutent sur le Mac, sans envoyer la dictée quotidienne à un service cloud."],["Vous attendez les résultats cloud ?","Les modèles locaux suppriment l’aller-retour vers les API et fonctionnent hors ligne."],["Les transcriptions brutes sont confuses ?","Un modèle Qwen local facultatif améliore ponctuation, phrases et style oral."],["Les raccourcis se déclenchent par erreur ?","Choisissez une touche ou combinaison et une durée d’appui pour préserver Control-C et les autres raccourcis."]],comparisonTitle:"CoveType face à la saisie vocale IA cloud",comparisonCapability:"Fonction",comparisonCloud:"Dictée cloud classique",comparisons:[["Voix vers texte","Local sur le Mac","Audio envoyé au serveur"],["Reformulation IA","Modèle Qwen local","Souvent un LLM cloud"],["Traduction","Apple sur l’appareil","Souvent une API distante"],["Compte","Non requis","Souvent requis"],["Code source","Open source GPLv3","Généralement propriétaire"]],
    privacyEyebrow:"CONFIDENTIALITÉ ET SÉCURITÉ",privacyTitle:"Un traitement local facile à comprendre.",privacyIntro:"La transcription et la reformulation quotidiennes n’appellent aucune API ASR ou de rédaction cloud. L’enregistrement commence seulement lorsque vous maintenez volontairement le raccourci configuré.",privacy:[["L’audio reste local","Les enregistrements temporaires sont traités sur le Mac puis supprimés en fin de traitement."],["Les modèles restent locaux","Qwen3-ASR et Qwen3.5 sont stockés dans les données locales de CoveType."],["Ni compte ni synchronisation","CoveType ne demande pas de connexion et ne synchronise pas l’historique des transcriptions."],["Autorisations limitées","Le microphone capture la voix ; Accessibilité gère le raccourci global et l’insertion dans l’application active."]],networkTitle:"Quand le réseau est-il utilisé ?",networkText:"La première installation télécharge l’environnement et les modèles épinglés. macOS télécharge les packs Apple Translation nécessaires et une recherche de mise à jour configurée peut contacter l’adresse de publication. La transcription et la reformulation courantes restent locales.",telemetryTitle:"Statistiques d’utilisation quotidiennes anonymes",telemetryText:"Activées par défaut et désactivables dans la fenêtre de retour du client. Au maximum une fois toutes les 24 heures, CoveType envoie par HTTPS un identifiant d’installation aléatoire, la version de l’app, la version de macOS et l’architecture du processeur. Cloudflare détermine seulement le pays ; CoveType ne conserve pas l’IP brute. Aucun audio, transcription ni texte saisi n’est inclus.",
    flowTitle:"Votre parcours voix-texte local",localFlow:[["Parlez","L’enregistrement démarre uniquement pendant l’appui sur votre raccourci."],["Transcription locale","Qwen3-ASR transforme la voix en texte sur le Mac."],["Reformulation locale","Qwen3.5 améliore facultativement la lisibilité sur l’appareil."],["Traduire ou saisir","Traduisez sur l’appareil ou insérez le résultat dans l’application active."]],openEyebrow:"OPEN SOURCE PAR CONCEPTION",openTitle:"Des promesses de confidentialité que vous pouvez vérifier.",openIntro:"Le code macOS de CoveType est public sous GPLv3. Examinez le démarrage de l’enregistrement, l’exécution des modèles, l’usage du réseau et l’insertion du texte.",viewSource:"Voir le code sur GitHub",proofs:[["Auditable","Inspectez le client Swift, l’IA locale, l’installateur, les mises à jour et les autorisations."],["Sans compte","La saisie vocale quotidienne ne demande ni inscription, ni identité d’abonnement, ni synchronisation."],["Réseau clairement délimité","Installation, packs de traduction, mises à jour et GitHub peuvent utiliser le réseau ; transcription et reformulation restent locales."]],
    languagesEyebrow:"LANGUES PRISES EN CHARGE",languagesTitle:"30 langues détectées automatiquement.",languagesIntro:"Voici la liste exacte annoncée par le modèle Qwen3-ASR installé. Le cantonais est distinct du chinois. Il n’est pas nécessaire de choisir la langue avant d’enregistrer.",translationTitle:"La traduction est une fonction distincte.",translationText:"Les 30 langues de reconnaissance ne garantissent pas 30 cibles de traduction identiques. Les paires Apple disponibles dépendent de la version de macOS, de la région et des packs installés.",
    installEyebrow:"TÉLÉCHARGEMENT ET INSTALLATION",installTitle:"Un installateur guidé pour Mac à puce Apple.",requirementsTitle:"Configuration",computer:"Ordinateur",computerValue:"Mac M1 ou puce Apple plus récente",system:"Système",memory:"Mémoire",memoryValue:"8 Go utilisables ; 16 Go recommandés",storage:"Stockage",storageValue:"Au moins 5 Go libres",firstInstall:"Première installation",firstInstallValue:"Connexion Internet ; aucun mot de passe administrateur requis",installSteps:[["Télécharger et décompresser","Téléchargez l’archive ZIP de CoveType et extrayez-la."],["Lancer l’installateur","Ouvrez « Install CoveType.command » : l’application, l’environnement isolé, les modèles et le démarrage automatique sont installés."],["Autoriser deux accès","Suivez le guide dans la langue du système pour activer Microphone et Accessibilité. L’installateur vérifie les deux."]],downloadBuild:"macOS 15+ · Puce Apple · ZIP notarié par Apple",downloadNow:"Télécharger",
    windowsEyebrow:"ÉTAT DE WINDOWS",windowsTitle:"L’application actuelle ne prend pas en charge Windows.",windowsIntro:"Le client dépend d’AppKit/SwiftUI, AVFoundation, Accessibilité, Apple Translation et MLX, propres à macOS. Il ne peut pas être copié ou reconditionné pour Windows.",windowsAvailableTitle:"Qu’est-ce qui fonctionne sous Windows aujourd’hui ?",windowsAvailableText:"Le dépôt contient un script Windows 10/11 x64 pour le backend officiel Qwen3-ASR PyTorch et une démo micro dans le navigateur. C’est un test de reconnaissance locale, pas encore une application de saisie globale.",windowsNeedsTitle:"Que faut-il pour une version Windows complète ?",windowsNeedsText:"Il faut un client .NET 8 séparé, l’enregistrement WASAPI, les raccourcis globaux et SendInput, un runtime PyTorch/ONNX, une solution de traduction locale, un installateur signé et des tests réels Windows 10/11. Cible pratique : x64, 8 Go de RAM minimum, 16 Go recommandés, 8 à 10 Go libres ; un GPU NVIDIA est facultatif mais réduit nettement la latence.",
    faqEyebrow:"DÉTAILS",faqTitle:"Avant l’installation",faqs:[["CoveType est-il une méthode de saisie macOS complète ?","Non. La version actuelle est un utilitaire vocal de barre des menus. Son raccourci global insère le texte dans l’application active sans changer de source de saisie."],["Pourquoi l’autorisation Accessibilité ?","macOS l’exige pour le raccourci global et l’insertion de texte dans une autre application. Vous pouvez la retirer à tout moment dans Réglages Système."],["La reformulation locale prend-elle en charge toutes les langues reconnues ?","Le petit modèle Qwen3.5 est multilingue, mais sa qualité n’est pas identique dans les 30 langues. Reconnaissance et qualité de reformulation sont distinctes : testez votre langue pour les usages importants."],["Tout est-il open source ?","Le code de l’application CoveType est sous GPLv3. Les modèles Qwen, paquets Python et frameworks Apple gardent leurs propres licences et conditions."]],footerTagline:"Saisie vocale privée, conçue pour votre Mac.",windowsStatusLink:"État de Windows"
  },
  de: {
    navFeatures:"Funktionen",navPrivacy:"Datenschutz",navLanguages:"Sprachen",navInstall:"Installation",languageSelector:"Webseitensprache",downloadShort:"Download",eyebrow:"PRIVAT · LOKAL · KI",heroTitle:"Ihre Stimme bleibt auf Ihrem Mac.",heroText:"Zum Sprechen Tastenkürzel halten, zum Schreiben loslassen. CoveType transkribiert lokal mit Qwen3-ASR, glättet Text optional mit lokaler KI und übersetzt über Apples On-Device-Framework.",downloadMac:"Für macOS laden",readPrivacy:"Datenschutz im Detail",appleSilicon:"Apple Chip (M1+)",noAccount:"Kein Konto",listening:"Hört zu",releaseToType:"Loslassen zum Transkribieren",processedLocally:"Lokal verarbeitet",
    seoTitle:"CoveType — Private KI-Spracheingabe für Mac",seoDescription:"Kostenlose Open-Source-KI-Spracheingabe für Mac: lokale Qwen-Transkription, private KI-Überarbeitung, 30 Sprachen und On-Device-Übersetzung.",navWhy:"Warum CoveType",navOpenSource:"Open Source",heroTitle:"Private KI-Spracheingabe für Mac. Ihre Stimme bleibt lokal.",heroText:"Tastenkürzel halten, sprechen und loslassen, um in jeder App zu schreiben. Qwen transkribiert und überarbeitet lokal, erkennt 30 Sprachen und unterstützt Apples On-Device-Übersetzung.",freeOpenSource:"Kostenlos & Open Source",
    featuresEyebrow:"FUNKTIONEN",featuresTitle:"Spracheingabe ohne Cloud-Umweg.",features:[["Lokale Transkription","Qwen3-ASR 0.6B 8-bit läuft auf Apple Chips und erkennt automatisch 30 Sprachen."],["Lokale KI-Überarbeitung","Qwen3.5 0.8B 4-bit verbessert Zeichensetzung, Satzgrenzen und gesprochene Formulierungen ohne Cloud-Schreib-API."],["Sofortübersetzung","Sprechen Sie eine Sprache und geben Sie eine andere über Apple Translation und geladene On-Device-Sprachpakete aus."],["Anpassbares Gedrückthalten","Erfassen Sie Taste oder Tastenkombination und Haltedauer, damit normale Kürzel keine Aufnahme starten."],["App-übergreifend","Beim Loslassen setzt CoveType das Ergebnis an der Cursorposition der aktuellen App ein."],["Für die Menüleiste","Eine kleine Atemlampe zeigt Leerlauf, Zuhören, Verarbeitung und Abschluss. Autostart bei Anmeldung ist möglich."]],
    painEyebrow:"FÜR ECHTE PROBLEME ENTWICKELT",painTitle:"KI-Diktat ohne typische Datenschutz- und Workflow-Kompromisse.",painIntro:"Cloud-Spracheingabe kann vertrauliche Sprache übertragen, Verzögerung verursachen, Rohtext liefern und Kürzel stören. CoveType wurde gegen diese Probleme entwickelt.",painPoints:[["Sorgen um Sprachdaten?","Erkennung und KI-Überarbeitung laufen auf dem Mac, statt tägliches Diktat an einen Cloud-Dienst zu senden."],["Warten auf Cloud-Ergebnisse?","Lokale Modelle vermeiden API-Rundreisen und funktionieren offline."],["Rohtranskripte unleserlich?","Ein optionales lokales Qwen-Modell verbessert Zeichensetzung und Formulierungen."],["Kürzel lösen versehentlich aus?","Taste oder Kombination und Haltedauer schützen Control-C und andere normale Kürzel."]],comparisonTitle:"CoveType im Vergleich zu typischem Cloud-Diktat",comparisonCapability:"Funktion",comparisonCloud:"Typisches Cloud-Diktat",comparisons:[["Sprache zu Text","Lokal auf dem Mac","Audio wird hochgeladen"],["KI-Überarbeitung","Lokales Qwen-Modell","Oft Cloud-LLM"],["Übersetzung","Apple On-Device","Oft entfernte API"],["Konto","Nicht nötig","Oft nötig"],["Quellcode","Open Source GPLv3","Meist proprietär"]],
    privacyEyebrow:"DATENSCHUTZ UND SICHERHEIT",privacyTitle:"Ein nachvollziehbarer lokaler Datenweg.",privacyIntro:"Die normale Transkription und KI-Überarbeitung rufen keine Cloud-ASR- oder Schreib-API auf. Aufgenommen wird erst, wenn das konfigurierte Kürzel bewusst gehalten wird.",privacy:[["Audio bleibt lokal","Temporäre Aufnahmen werden auf dem Mac verarbeitet und nach Abschluss gelöscht."],["Modelle bleiben lokal","Qwen3-ASR und Qwen3.5 liegen in den lokalen CoveType-App-Daten."],["Kein Konto, keine Synchronisierung","CoveType benötigt keine Anmeldung und synchronisiert keinen Transkriptverlauf."],["Begrenzte Berechtigungen","Das Mikrofon erfasst Sprache; Bedienungshilfen dienen dem globalen Kürzel und der Texteingabe in die aktive App."]],networkTitle:"Wann wird das Netzwerk genutzt?",networkText:"Bei der Erstinstallation werden festgelegte Laufzeit und Modelle geladen. macOS lädt benötigte Apple-Translation-Sprachpakete; eine konfigurierte Updateprüfung kann den Veröffentlichungsserver kontaktieren. Normale Transkription und Überarbeitung bleiben lokal.",telemetryTitle:"Anonyme tägliche Nutzungsstatistik",telemetryText:"Standardmäßig aktiviert und im Feedback-Fenster des Clients abschaltbar. Höchstens einmal in 24 Stunden sendet CoveType eine zufällige Installations-ID, App-Version, macOS-Version und Prozessorarchitektur per HTTPS. Cloudflare bestimmt nur das Land; CoveType speichert die rohe IP nicht. Audio, Transkripte und eingegebener Text sind nie enthalten.",
    flowTitle:"Ihr lokaler Sprache-zu-Text-Weg",localFlow:[["Sprechen","Aufnahme nur solange das gewählte Kürzel gehalten wird."],["Lokal transkribieren","Qwen3-ASR wandelt Sprache auf dem Mac in Text um."],["Lokal überarbeiten","Optional verbessert Qwen3.5 die Lesbarkeit auf dem Gerät."],["Übersetzen oder eingeben","On-Device übersetzen oder in die aktive App einsetzen."]],openEyebrow:"OPEN SOURCE ENTWICKELT",openTitle:"Datenschutz, den Sie prüfen können.",openIntro:"Der macOS-App-Code von CoveType ist unter GPLv3 öffentlich. Prüfen Sie Aufnahme, Modellausführung, Netzwerkzugriffe und Texteingabe.",viewSource:"Quellcode auf GitHub ansehen",proofs:[["Prüfbar","Swift-Client, lokale KI, Installer, Updatekanal und Berechtigungen sind einsehbar."],["Kein Konto","Alltägliche Spracheingabe braucht keine Registrierung, Abo-Identität oder Synchronisierung."],["Klare Netzwerkgrenze","Installation, Übersetzungspakete, Updates und GitHub können online sein; Erkennung und Überarbeitung bleiben lokal."]],
    languagesEyebrow:"SPRACHUNTERSTÜTZUNG",languagesTitle:"30 Sprachen automatisch erkannt.",languagesIntro:"Dies ist die exakte Liste des installierten Qwen3-ASR-Modells. Kantonesisch wird getrennt von Chinesisch geführt. Vor der Aufnahme ist keine Sprachauswahl nötig.",translationTitle:"Übersetzung ist eine separate Funktion.",translationText:"30 Erkennungssprachen bedeuten nicht automatisch dieselben 30 Übersetzungsziele. Verfügbare Apple-Sprachpaare hängen von macOS-Version, Region und installierten Paketen ab.",
    installEyebrow:"DOWNLOAD UND INSTALLATION",installTitle:"Geführte Installation für Apple-Silicon-Macs.",requirementsTitle:"Voraussetzungen",computer:"Computer",computerValue:"Mac mit M1 oder neuerem Apple Chip",system:"System",memory:"Arbeitsspeicher",memoryValue:"8 GB nutzbar; 16 GB empfohlen",storage:"Speicher",storageValue:"Mindestens 5 GB frei",firstInstall:"Erstinstallation",firstInstallValue:"Internetverbindung; kein Administratorpasswort erforderlich",installSteps:[["Laden und entpacken","CoveType-Installer-ZIP laden und entpacken."],["Installer starten","„Install CoveType.command“ öffnen. App, isolierte Laufzeit, Modelle und Autostart werden eingerichtet."],["Zwei Berechtigungen erteilen","Der Anleitung in Systemsprache folgen und Mikrofon sowie Bedienungshilfen aktivieren. Der Installer prüft beides."]],downloadBuild:"macOS 15+ · Apple Chip · Von Apple notarisiertes ZIP",downloadNow:"Jetzt laden",
    windowsEyebrow:"WINDOWS-STATUS",windowsTitle:"Die aktuelle App unterstützt Windows nicht.",windowsIntro:"Der Client nutzt macOS-spezifisches AppKit/SwiftUI, AVFoundation, Bedienungshilfen, Apple Translation und MLX. Er kann nicht für Windows kopiert oder neu verpackt werden.",windowsAvailableTitle:"Was funktioniert heute unter Windows?",windowsAvailableText:"Das Quellprojekt enthält eine Windows-10/11-x64-Einrichtung für das offizielle Qwen3-ASR-PyTorch-Backend und eine Browser-Mikrofondemo. Das ist ein lokaler Erkennungstest, noch keine systemweite Tray-Eingabe-App.",windowsNeedsTitle:"Was braucht eine vollständige Windows-Version?",windowsNeedsText:"Nötig sind ein eigener .NET-8-Client, WASAPI-Aufnahme, globale Windows-Tasten und SendInput, PyTorch/ONNX-Laufzeit, lokale Übersetzung, signierter Installer und Tests auf echten Windows-10/11-Geräten. Praxisziel: x64, mindestens 8 GB RAM, 16 GB empfohlen, 8–10 GB frei; NVIDIA-GPU optional, aber deutlich schneller.",
    faqEyebrow:"DETAILS",faqTitle:"Vor der Installation",faqs:[["Ist CoveType eine vollständige macOS-Eingabemethode?","Nein. Die aktuelle Version ist ein Menüleisten-Sprachwerkzeug. Das globale Haltekürzel fügt Text in die aktive App ein, ohne die Eingabequelle zu wechseln."],["Warum ist Bedienungshilfen-Zugriff nötig?","macOS verlangt ihn für globale Kürzel und Texteingabe in eine andere App. Er kann jederzeit in den Systemeinstellungen entzogen werden."],["Funktioniert lokale Überarbeitung in allen Erkennungssprachen?","Das kleine Qwen3.5-Modell ist mehrsprachig, aber nicht in allen 30 Sprachen gleich gut. Erkennung und Überarbeitungsqualität sind getrennt; wichtige Sprachen sollten getestet werden."],["Ist alles Open Source?","Der CoveType-App-Code steht unter GPLv3. Qwen-Modelle, Python-Pakete und Apple-Frameworks haben eigene Lizenzen und Bedingungen."]],footerTagline:"Private Spracheingabe für Ihren Mac.",windowsStatusLink:"Windows-Status"
  },
  es: {
    navFeatures:"Funciones",navPrivacy:"Privacidad",navLanguages:"Idiomas",navInstall:"Instalación",languageSelector:"Idioma del sitio",downloadShort:"Descargar",eyebrow:"PRIVADO · LOCAL · IA",heroTitle:"Tu voz permanece en tu Mac.",heroText:"Mantén un atajo para hablar y suéltalo para escribir. CoveType transcribe con Qwen3-ASR local, puede mejorar el texto con IA local y traducir mediante el sistema de Apple en el dispositivo.",downloadMac:"Descargar para macOS",readPrivacy:"Ver detalles de privacidad",appleSilicon:"Chip de Apple (M1+)",noAccount:"Sin cuenta",listening:"Escuchando",releaseToType:"Suelta para transcribir y escribir",processedLocally:"Procesado localmente",
    seoTitle:"CoveType — Dictado por voz con IA privada para Mac",seoDescription:"Dictado con IA gratis y de código abierto para Mac: voz a texto Qwen local, mejora privada, 30 idiomas y traducción en el dispositivo.",navWhy:"Por qué CoveType",navOpenSource:"Código abierto",heroTitle:"Dictado por voz con IA privada para Mac. Tu voz permanece local.",heroText:"Mantén un atajo, habla y suelta para escribir en cualquier aplicación. Qwen transcribe y mejora localmente, detecta 30 idiomas y admite traducción Apple en el dispositivo.",freeOpenSource:"Gratis y de código abierto",
    featuresEyebrow:"FUNCIONES",featuresTitle:"Entrada de voz sin pasar por la nube.",features:[["Transcripción local","Qwen3-ASR 0.6B 8-bit funciona en chips de Apple y detecta automáticamente 30 idiomas."],["Mejora con IA local","Qwen3.5 0.8B 4-bit mejora puntuación, frases y estilo oral sin una API de escritura en la nube."],["Traducción instantánea","Habla en un idioma y produce otro con Apple Translation y paquetes descargados en el dispositivo."],["Pulsar para hablar configurable","Graba una tecla o combinación y define cuánto mantenerla para evitar activaciones accidentales."],["Funciona entre aplicaciones","Al soltar el atajo, CoveType inserta el resultado donde está el cursor en la aplicación actual."],["Diseñado para la barra de menús","Una pequeña luz indica reposo, escucha, proceso y fin. CoveType puede iniciarse al entrar en la sesión."]],
    painEyebrow:"DISEÑADO PARA PROBLEMAS REALES",painTitle:"Dictado con IA sin sacrificar privacidad ni flujo de trabajo.",painIntro:"La voz en la nube puede exponer contenido sensible, añadir latencia, producir texto desordenado y molestar atajos. CoveType aborda esos problemas.",painPoints:[["¿Te preocupa la privacidad de tu voz?","El reconocimiento y la mejora con IA funcionan en el Mac sin enviar el dictado diario a un servicio en la nube."],["¿Esperas resultados de la nube?","Los modelos locales eliminan el viaje a API remotas y funcionan sin conexión."],["¿Las transcripciones necesitan limpieza?","Un modelo Qwen local opcional mejora puntuación, frases y lenguaje oral."],["¿Los atajos se activan por error?","Configura una tecla o combinación y el tiempo de pulsación para proteger Control-C y otros atajos."]],comparisonTitle:"CoveType frente al dictado típico en la nube",comparisonCapability:"Función",comparisonCloud:"Dictado típico en la nube",comparisons:[["Voz a texto","Local en el Mac","Audio subido al servidor"],["Mejora con IA","Modelo Qwen local","Suele usar un LLM en la nube"],["Traducción","Apple en el dispositivo","Suele usar API remota"],["Cuenta","No requerida","Suele ser necesaria"],["Código fuente","GPLv3 abierto","Normalmente propietario"]],
    privacyEyebrow:"PRIVACIDAD Y SEGURIDAD",privacyTitle:"Una ruta de proceso local fácil de entender.",privacyIntro:"La transcripción y la mejora diarias no llaman a servicios ASR ni de escritura en la nube. La grabación solo empieza al mantener intencionadamente el atajo configurado.",privacy:[["El audio permanece local","Las grabaciones temporales se procesan en el Mac y se eliminan al finalizar."],["Los modelos permanecen locales","Qwen3-ASR y Qwen3.5 se guardan en los datos locales de CoveType."],["Sin cuenta ni sincronización","CoveType no requiere iniciar sesión ni sincroniza el historial de transcripciones."],["Permisos limitados","El micrófono captura la voz; Accesibilidad gestiona el atajo global y la inserción en la aplicación activa."]],networkTitle:"¿Cuándo se usa la red?",networkText:"La primera instalación descarga el entorno y los modelos fijados. macOS descarga los paquetes de Apple Translation cuando hacen falta y una comprobación de actualizaciones configurada puede contactar el canal de versiones. La transcripción y la mejora normales siguen siendo locales.",telemetryTitle:"Estadísticas anónimas de uso diario",telemetryText:"Activadas de forma predeterminada y desactivables en la ventana de comentarios del cliente. Como máximo una vez cada 24 horas, CoveType envía por HTTPS un ID de instalación aleatorio, la versión de la app, la versión de macOS y la arquitectura del procesador. Cloudflare determina solo el país; CoveType no guarda la IP original. Nunca incluye audio, transcripciones ni texto escrito.",
    flowTitle:"Tu ruta local de voz a texto",localFlow:[["Habla","Solo se graba mientras mantienes el atajo elegido."],["Transcribe localmente","Qwen3-ASR convierte voz en texto en el Mac."],["Mejora localmente","Qwen3.5 opcional mejora la legibilidad en el dispositivo."],["Traduce o escribe","Traduce en el dispositivo o inserta el resultado en la aplicación activa."]],openEyebrow:"CÓDIGO ABIERTO POR DISEÑO",openTitle:"Privacidad que puedes inspeccionar, no solo creer.",openIntro:"El código macOS de CoveType es público bajo GPLv3. Revisa cuándo graba, dónde ejecuta modelos, cuándo usa la red y cómo inserta texto.",viewSource:"Ver código en GitHub",proofs:[["Auditable","Revisa el cliente Swift, IA local, instalador, canal de actualización y permisos."],["Sin cuenta","El dictado diario no requiere registro, identidad de suscripción ni sincronización."],["Límite de red claro","Instalación, idiomas, actualizaciones y GitHub pueden usar red; reconocimiento y mejora siguen locales."]],
    languagesEyebrow:"IDIOMAS COMPATIBLES",languagesTitle:"Detección automática de 30 idiomas.",languagesIntro:"Esta es la lista exacta del modelo Qwen3-ASR instalado. El cantonés figura separado del chino. No es necesario elegir el idioma antes de grabar.",translationTitle:"La traducción es una función independiente.",translationText:"Los 30 idiomas de reconocimiento no garantizan los mismos 30 destinos de traducción. Los pares disponibles de Apple dependen de la versión de macOS, la región y los paquetes instalados.",
    installEyebrow:"DESCARGA E INSTALACIÓN",installTitle:"Instalador guiado para Mac con chip de Apple.",requirementsTitle:"Requisitos",computer:"Ordenador",computerValue:"Mac M1 o chip de Apple posterior",system:"Sistema",memory:"Memoria",memoryValue:"8 GB funcionales; 16 GB recomendados",storage:"Almacenamiento",storageValue:"Al menos 5 GB libres",firstInstall:"Primera instalación",firstInstallValue:"Conexión a Internet; no requiere contraseña de administrador",installSteps:[["Descarga y descomprime","Descarga el ZIP del instalador de CoveType y extráelo."],["Ejecuta el instalador","Abre «Install CoveType.command». Instala la aplicación, el entorno aislado, los modelos y el inicio de sesión."],["Autoriza dos permisos","Sigue la guía en el idioma del sistema para activar Micrófono y Accesibilidad. El instalador comprueba ambos."]],downloadBuild:"macOS 15+ · Chip de Apple · ZIP notarizado por Apple",downloadNow:"Descargar ahora",
    windowsEyebrow:"ESTADO DE WINDOWS",windowsTitle:"La aplicación actual no es compatible con Windows.",windowsIntro:"El cliente depende de AppKit/SwiftUI, AVFoundation, Accesibilidad, Apple Translation y MLX, exclusivos de macOS. No puede copiarse ni reempaquetarse para Windows.",windowsAvailableTitle:"¿Qué funciona hoy en Windows?",windowsAvailableText:"El repositorio incluye un instalador para Windows 10/11 x64 del backend oficial Qwen3-ASR con PyTorch y una demo de micrófono en el navegador. Es una prueba de reconocimiento local, no una aplicación de entrada global en la bandeja.",windowsNeedsTitle:"¿Qué requiere una versión completa para Windows?",windowsNeedsText:"Hace falta un cliente .NET 8 independiente, grabación WASAPI, atajos globales y SendInput, entorno PyTorch/ONNX, traducción local alternativa, instalador firmado y pruebas reales en Windows 10/11. Objetivo práctico: x64, 8 GB de RAM mínimo, 16 GB recomendados, 8–10 GB libres; GPU NVIDIA opcional pero mucho más rápida.",
    faqEyebrow:"DETALLES",faqTitle:"Antes de instalar",faqs:[["¿CoveType es un método de entrada completo de macOS?","No. La versión actual es una utilidad de voz de la barra de menús. El atajo global inserta texto en la aplicación activa sin cambiar la fuente de entrada."],["¿Por qué necesita permiso de Accesibilidad?","macOS lo exige para el atajo global y para insertar texto en otra aplicación. Puedes retirarlo en cualquier momento desde Ajustes del Sistema."],["¿La mejora local admite todos los idiomas de reconocimiento?","El pequeño modelo Qwen3.5 es multilingüe, pero la calidad no es idéntica en los 30 idiomas. Reconocimiento y calidad de mejora son distintos; prueba tu idioma en usos importantes."],["¿Todo es código abierto?","El código de CoveType se distribuye bajo GPLv3. Los modelos Qwen, paquetes Python y frameworks de Apple mantienen sus propias licencias y condiciones."]],footerTagline:"Entrada de voz privada para tu Mac.",windowsStatusLink:"Estado de Windows"
  }
};

for (const [locale, translated] of Object.entries(additionalLocales)) {
  locales[locale] = { ...english, ...translated };
}


const textKeys = [
  "navFeatures","navWhy","navPrivacy","navLanguages","navOpenSource","navInstall","languageSelector","downloadShort","eyebrow","heroTitle","heroText","downloadMac","readPrivacy","appleSilicon","noAccount","freeOpenSource","listening","releaseToType","processedLocally","painEyebrow","painTitle","painIntro","comparisonTitle","comparisonCapability","comparisonCloud","featuresEyebrow","featuresTitle","privacyEyebrow","privacyTitle","privacyIntro","networkTitle","networkText","telemetryTitle","telemetryText","flowTitle","openEyebrow","openTitle","openIntro","viewSource","languagesEyebrow","languagesTitle","languagesIntro","translationTitle","translationText","installEyebrow","installTitle","requirementsTitle","computer","computerValue","system","memory","memoryValue","storage","storageValue","firstInstall","firstInstallValue","downloadBuild","downloadNow","windowsEyebrow","windowsTitle","windowsIntro","windowsAvailableTitle","windowsAvailableText","windowsNeedsTitle","windowsNeedsText","faqEyebrow","faqTitle","footerTagline","windowsStatusLink"
];

const localePaths = {
  en: "",
  "zh-Hans": "zh-cn/",
  "zh-Hant": "zh-tw/",
  ja: "ja/",
  ko: "ko/",
  fr: "fr/",
  de: "de/",
  es: "es/"
};

if (typeof module !== "undefined") {
  module.exports = { supportedLanguages, locales, textKeys, localePaths };
}

if (typeof document !== "undefined") {
  const selector = document.getElementById("locale");
  const currentLocale = document.documentElement.dataset.locale || "en";
  const rootPath = document.documentElement.dataset.root || ".";
  selector.value = currentLocale;
  selector.addEventListener("change", (event) => {
    const selected = locales[event.target.value] ? event.target.value : "en";
    const destination = localePaths[selected];
    const suffix = location.hash || "";
    location.href = destination ? `${rootPath}/${destination}${suffix}` : `${rootPath}/${suffix}`;
  });
}
